### PR TITLE
`TrustedEntitlements`: measure performance using `TimingUtil`

### PR DESCRIPTION
**Pull request by NachoSoto**
Depends on #2715 and #2716.

### CODE REVIEW

**Comment by NachoSoto** [comment]
I'll close this since I don't think it's that useful now that we know it's really fast.

**Review by aboedo — COMMENTED** [review]
in practice this shouldn't happen, right? 
I wonder if we can just actually test this with the slowest supported device and an artificially huge receipt (or a modified version of a really large receipt) to see how it goes.

**Comment by aboedo** [comment]
mostly wondering because the 0.5 seconds threshold seems arbitrary and device-specific

**Comment by NachoSoto** [comment]
Yeah I debated whether we actually need it. I only did it to measure the performance myself, and was thinking that if it happens to be slow in the wild in an old device, this would be a way to know.
I was envisioning the possibility of maybe `Curve25519` being too slow in some version of iOS 13 or something.

> with the slowest supported device
We'd have to do it with a physical device though.

**Comment by NachoSoto** [comment]
I'll just close this since I don't think it's that useful.

**Pull request closed without merging**
