### PR TITLE
Feature: xcframeworks

### PR DESCRIPTION
**Pull request by aboedo**
Adds support for building xcframeworks. 
Automatically builds and uploads an xcframework to releases, alongside the old universal framework. \

This should provide seamless compatibility for macOS / macCatalyst and Apple Sillicon for developers who integrate the framework directly through the binary. 
For folks who use other mechanisms: 
- Carthage: updating to Carthage v0.37+ should already provide seamless compatibility
- Cocoapods: was already working correctly for all architectures
- Swift Package Manager: was already working correctly for all architectures
- Xcode direct integration: I believe that since there's no concept of an `XCFramework` target in Xcode, you'd have to create the XCFramework yourself. This can be done by running (from the project dir) `bundle exec fastlane export_xcframework`.

### CODE REVIEW

**Review by vegaro — APPROVED** [review]

**Comment by fishandphil** [comment]
Good evening @vegaro & @aboedo

We downloaded and tried the release XCFramework and got the attached code signing issue when trying to run our Catalyst app on our Macs with the new XCFramework. 

Screenshot 2021-02-18 at 20 05 31

What do you think ? :)

Thank you

**Comment by aboedo** [comment]
hey @fishandphil thanks for trying it out so quickly! I'll take a look to see if I can figure out what's going on

**Comment by aboedo** [comment]
@fishandphil I believe this is happening because we're not signing the framework (so that it doesn't get tied to our development team), but you're not signing it either, so it's unsigned, which Xcode doesn't like. 

Could you try updating the config in your project in `General` -> `Frameworks, Libraries and Embedded Content` to `Embed & Sign`? 

| Before | After |
| :-: | :-: |
| Screen Shot 2021-02-18 at 5 10 16 PM | Screen Shot 2021-02-18 at 5 10 20 PM |

**Comment by fishandphil** [comment]
Thanks @aboedo for your prompt answer. 
We're already using a few third-parties XCFramework in our projects coming from Facebook or Google (works perfectly). The error appears when set to "Embed & Sign" as you can see attached. 

Let me know if we can provide you with anything else in order to get going! 

Screenshot 2021-02-18 at 21 21 22

**Comment by aboedo** [comment]
have you deleted derived data? I'm not sure why xcode sees no signing at all for the object. I'm messing around with settings in my own project and can't find a way to reproduce other than setting embed without signing. still trying things though.

**Comment by fishandphil** [comment]
Good morning @aboedo 

We've deleted our derived data, cleaned and tried again. The error is still there.

**Comment by aboedo** [comment]
@fishandphil I'm still trying to reproduce, don't give up on me! I'm not sure what exactly is going on since we build the SDK without signing it at all.

**Comment by aboedo** [comment]
@fishandphil could you please try the following? 
`cd` into the `Purchases.xcframework` location, then 

```bash
 xattr -lr Purchases.xcframework
```
then clean and build? 

I managed to reproduce in a Catalyst app and this fixed it for me. If this was the problem I'll add it to CI so you don't have to do it manually

**Comment by aboedo** [comment]
update: the issue is probably related to `xcattrs` getting added in the process of downloading the `xcframework`, specifically in Catalyst. 
I confirmed that if I download the `xcframework` from github for a Catalyst app, I get that exact same error. However, if I instead use the `xcframework` generated from my computer (it's the same one I uploaded to github, but nothing got added because it wasn't downloaded), it works correctly. 

I think this is essentially the same that happens here: https://pspdfkit.com/guides/ios/current/knowledge-base/gatekeeper-alerts-mac-catalyst/ where PSPDFKit solves it by adding an extra run script phase. I'll try that out and update here.

**Comment by aboedo** [comment]
update: found it. and while I think we might still need to clear `xattr`s if you download using Safari, the real problem was when actually compressing the xcframework 🤦 

Turns out that `fastlane zip` seems to create copies of files that are symlinked instead of keeping the symlinks, and this breaks signing. 
I'm uploading a new version of the zip. I'll also fix the CI process. Please give it another shot!

**Comment by aboedo** [comment]
Uploaded, it's the `xcframework` file in the 3.10.4 release. Let me know how it goes!

**Comment by fishandphil** [comment]
Hi @aboedo 
Thank you 

I have downloaded the new XCFramework. Cleaned run on the Mac. The app launches but with the strange security message:

Screenshot 2021-02-20 at 08 12 01

It launches our App if I touch the Cancel button. 
Also want to highlight that it shows in the Security & Privacy view of the System Preferences

Screenshot 2021-02-20 at 08 21 40

I have tried "xattr -cr Purchases.xcframework" but it doesn't change anything. 

At the end, I have allowed the framework from System Preferences but I think it is a strange integration step :) I'll try later to validate & submit an iOS & Catalyst archive to the App Store and let you know if it goes smoothly or not :)

**Comment by fishandphil** [comment]
@aboedo running our app locally from Xcode works well. However, we're unable to validate or upload an archive to App Store Connect. 
Did you manage to do so? with the XCFramework downloaded from Github?

**Comment by aboedo** [comment]
@fishandphil thanks for trying it out and reporting back! And for the patience while we work out the kinks with xcframeworks and Catalyst. 

I guess the error does sort of make sense given that it's unsigned. I can try actually signing it and uploading a signed version that you can then re-sign. I believe the actual issue is this: 
> Xcode is finding the XCFrameworks extracted frameworks in the build directory and trying to link them instead of the signed frameworks in the app bundle

(from https://pspdfkit.com/guides/ios/current/knowledge-base/gatekeeper-alerts-mac-catalyst). 
that would explain why Xcode still sees the framework as unsigned. 
What error message do you get when validating the ipa? Is it also related to having an unsigned framework?

I'm happy to try uploading a signed copy of the framework on Monday and see how that goes. 
Note that this shouldn't be an issue once it's on the App Store, since Apple re-signs all apps with their private key anyway, so everything gets a single signature.

**Comment by aboedo** [comment]
@fishandphil I'm currently running into an error `"Code signing "A" failed."` when trying to validate the archive. I'm not quite sure how to work around it. Some people ([here](https://developer.apple.com/forums/thread/666269) and [here](https://adrian.schoenig.me/blog/2019/10/21/carthage-and-catalyst/)) suggest it gets fixed by going into build settings, finding `Enable Bitcode` and deleting the setting (i.e.: going back to default), which supposedly works around and xcode bug. It doesn't seem to work for my case, though, so I'm still in the process of figuring this out.

**Comment by aboedo** [comment]
@fishandphil I uploaded a new build without bitcode. This one passes validation for me, hope it works for you! [file in the 3.10.4 release](https://github.com/RevenueCat/purchases-ios/releases/download/3.10.4/Purchases.xcframework.zip) Let me know how it goes so I can update our CI to use the same settings!

**Comment by fishandphil** [comment]
Good evening @aboedo 
Sorry for not responding sooner! We were able to archive, validate & upload a Catalyst version of our app to App Store Connect. This is awesome. Thank you very much. 
We'll try the same with our iOS version tomorrow. If everything goes well, it will be deployed Live later this week on the App Store. 
Awesome job!

**Comment by fishandphil** [comment]
Hi @aboedo 

We tried to build/archive/upload our iOS version with our CI and we get the following error: 

> 1 package(s) were not uploaded because they had problems:
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/B4A6724F-61BB-4CA1-B10A-2728E4FB74E1/935623257.itmsp - Error Messages:
		ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3.11.0-SNAPSHOT' in the Info.plist file at '${bundlePath}' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

Is there a reason why the "Bundle version string (short)" is "3.11.0-SNAPSHOT" within RC's framework?

Screenshot 2021-02-23 at 09 25 54

Can you look into it? :)

**Comment by aboedo** [comment]
@fishandphil my apologies, I made the build off of the wrong git commit 🤦 . 
We use `SNAPSHOT` to identify development versions of the SDK, as opposed to release versions. 
I just made a build off of the correct commit (double-checked) and replaced the one in the release, this one should work. 

Once again, thank you so much for your patience. Future builds will all come from CI, which doesn't make the same dumb mistakes I do, so hopefully we won't run into these issues again.

**Comment by fishandphil** [comment]
@aboedo everything working smoothly now with our CI. Thank you. 
Good job! will be deployed in our next release.

**Comment by aboedo** [comment]
That's great to hear! Thanks for testing and reporting back! You've been a huge help in getting this out 💪

**Comment by fishandphil** [comment]
In the future, if you could think of fixing the following warning message which is not great UX / confusing for devs: 

Screenshot 2021-02-24 at 15 37 03

**Comment by aboedo** [comment]
that message is a total bummer. have you tried setting up a build phase for removing the quarantine xattribute? 
i.e.: 

https://pspdfkit.com/guides/ios/current/knowledge-base/gatekeeper-alerts-mac-catalyst/

If that works, I can add it to the docs. 

Safari does add the xattribute, I'm not sure about other browsers, but downloading with `wget` didn't seem to have this problem for me.

**Comment by fishandphil** [comment]
My assumption is that we use XCFramework downloaded from the release page of Github such as the "firebase.zip" file here: https://github.com/firebase/firebase-ios-sdk/releases 

and it does not show this warning at all, ever. This is the first time that we experience this. So, there should be a way to avoid it on your side :)

**Comment by aboedo** [comment]
Hey @fishandphil sorry for the late reply. 
I've been playing around with 2 theories of why this might happen, but they didn't quite pan out. I figured either:
- Firebase's xcframework was codesigned, so mac would trust it (but `codesign --verify --verbose` says it's not, maybe there's a different way to check?)
- Firebase had figured out a way around Safari's quarantine, but doing `xattrs -lr` did show some quarantined files as well for Firebase. 

I'll add an item to the backlog to do some further research on this and figure out what's going on. Thanks again for everything!

**Pull request merged**
