### PR TITLE
Set base SDK to iOS to fix Catalyst build

### PR DESCRIPTION
**Pull request by douglashill**
We use direct Xcode project integration for Purchases in our app PDF Viewer (i.e. no Swift Package Manager or anything). After updating to 3.7.2, building for Mac Catalyst was failing with this error:

> Building for Mac Catalyst, but the linked framework 'Purchases.framework' is building for macOS. You may need to configure 'Purchases.framework' to build for Mac Catalyst or restrict the platforms for which this framework should be linked in the target editor.

It seems that if the SDKROOT (base SDK) is the default value (macOS), then when building for iOS Xcode infers actually the iOS SDK should be used but when building for Mac Catalyst Xcode uses the macOS SDK instead of the Mac Catalyst SDK for some reason.

I have not tested this with any other integration methods: I’m just providing what worked for us. It seems likely this might break regular macOS builds of Purchases, and if this is the case obviously this PR should be discarded. We’ll just have to apply this patch each time we update if this ends up being the case.

### CODE REVIEW

**Comment by aboedo** [comment]
Thanks for opening!

ha, another case where this caused issues in the past - I believe it was when exporting XCFrameworks. But then that got removed anyhow. 

Like the other PR, I'll test it out on all package managers to ensure they don't break before merging. Thanks again for opening!

**Comment by douglashill** [comment]
Yeah we’ve also had various issues getting XCFrameworks working in all cases. Thanks for looking into this!

**Comment by aboedo** [comment]
@douglashill just a heads up that I haven't forgotten about this one, I'll be testing it out and merging soon. Thanks for your patience.

**Comment by aboedo** [comment]
finally got some time to test this, and it seems to work correctly on macOS native apps as well as Catalyst. 

@douglashill thanks again for opening and for your patience!

**Pull request merged**
