### PR TITLE
Fix transaction metadata in purchase tester app

### PR DESCRIPTION
**Pull request by fire-at-will**
We decided to place the transaction metadata feature behind the ENABLE_TRANSACTION_METADATA flag, but didn't update the Purchase Tester app, so we broke the app's compilation. This PR fixes temporarily fixes that :)

### CODE REVIEW

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Review by MarkVillacampa — APPROVED** [review]

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Pull request merged**
