### PR TITLE
fix typo in comment

### PR DESCRIPTION
**Pull request by aboedo**
not exactly the most complex PR I've ever made 😂 but I saw it and figured it's better to open it before I forget

### CODE REVIEW

**Comment by aboedo** [comment]
I always forget to add [skip-ci] 🤦

**Review by taquitos — APPROVED** [review]
Amazing PR. HUGE IMPACT, WOW
😆

**Review by NachoSoto — APPROVED** [review]
Can you add a test? 🙃

**Comment by aboedo** [comment]
@NachoSoto I'm working on a fastlane action that will scan the entire repo for `quanity` and replace it with `quantity` and make a PR for each line, then a test that checks that there are no instances of `quanity`, and a test that checks that replacing goes correctly. :trollface: 
but I'll do that as a separate PR

**Pull request merged**
