### PR TITLE
Fix typos (in comments)

### PR DESCRIPTION
**Pull request by MortenGregersen**
### Checklist
- [x] If applicable, unit tests
- [x] If applicable, create follow-up issues for `purchases-android` and hybrids

### Motivation
I found some extra f-ses.

### Description
I just removed them.

### CODE REVIEW

**Review by NachoSoto — CHANGES_REQUESTED** [review]
Thanks, but this is on purpose: https://en.wikipedia.org/wiki/If_and_only_if

**Comment by MortenGregersen** [comment]
Fine 👍 Never heard of it.

**Review by aboedo — COMMENTED** [review]
maybe we could explicitly update to `if and only if`, since I'm not sure `iff` is that well-known

**Comment by aboedo** [comment]
at least for public-facing stuff

**Pull request closed without merging**
