### PR TITLE
Release 4.10.1

### PR DESCRIPTION
**Pull request by joshdholtz**
### Bugfixes
* Directly send delegate customer info when delegate is set (always sends cached CustomerInfo value) (#1828) via Josh Holtz (@joshdholtz)

### CODE REVIEW

**Review by aboedo — APPROVED** [review]
🚢 it (without merging) when tests pass

**Comment by joshdholtz** [comment]
@aboedo Do I just close this PR then? 🤔

**Comment by aboedo** [comment]
@joshdholtz this is already out right? We can close this PR if that's the case

**Comment by joshdholtz** [comment]
Ah yes, whoops! Thought I closed 🤦‍♂️ Thanks for reminder!

**Comment by NachoSoto** [comment]
This should have been merged into `main`, right? We're missing this changelog.

**Comment by NachoSoto** [comment]
I just manually added this changelog in #1848.

**Pull request closed without merging**
