### PR TITLE
[AUTOMATIC] Release/4.13.3

### PR DESCRIPTION
**Pull request by revenuecat-ops**
**This is an automatic release.**

### Other Changes
* `TrialOrIntroPriceEligibilityChecker`: only use SK2 implementation if enabled (#1984) via NachoSoto (@NachoSoto)

### CODE REVIEW

**Comment by NachoSoto** [comment]
Heads up #1982 already went out in the last release, I cherry-picked it to the release branch.

**Review by NachoSoto — APPROVED** [review]

**Comment by NachoSoto** [comment]
Updated changelog and cherry-picked #1991 to fix CI.

**Comment by NachoSoto** [comment]
@vegaro the first `make-release` failed, but it actually submitted it: https://github.com/CocoaPods/Specs/commit/8ecdd9631cae72ebb5ce29fe6363ca70b1a7c8da

How do we suggest we restart it but skipping `push_pods`?

```ruby
desc "Release to CocoaPods, create Carthage archive, export XCFramework, and create GitHub release"
  lane :release do |options|
    version_number = current_version_number
    push_pods
    carthage_archive
    export_xcframework
    github_release(version: version_number)
  end

**Comment by aboedo** [comment]
you can have a single commit that comments out that line and enables the job for that commit, or run it manually from your computer (but you'd need to set up env vars). 
the single commit approach should work fine, since the xcframework and github releases will be the same with that line change

**Pull request merged**
