### PR TITLE
Bump deployment target to `iOS 13` / `tvOS 13` / `macOS 10.15`

### PR DESCRIPTION
**Pull request by NachoSoto**
See https://github.com/RevenueCat/purchases-ios/blob/1fd2736217c94ec025f5e44724f978505f4a84c0/Contributing/UpdatingRequirements.md

### After this PR:
- #3616 
- Update deployment target on PHC and hybrids
- Update https://github.com/RevenueCat/revenuecat-docs/blob/main/docs_source/Getting%20Started/installation/ios.md
- Update https://github.com/RevenueCat/revenuecat-docs/blob/main/docs_source/Getting%20Started/installation/macos.md

### CODE REVIEW

**Comment by NachoSoto** [comment]
Holding until we're ready to release the major with #3582 and #3529.

**Review by MarkVillacampa — APPROVED** [review]
YAY!

**Comment by MarkVillacampa** [comment]
iOS 15 tests seem to be failing consistently here:

```
Testing failed:
        UnitTestsHostApp (8762) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying Error: Crash: UnitTestsHostApp (8762) type metadata completion function for MockStoreMessage. If you believe this error represents a bug, please attach the result bundle at /Users/distiller/purchases-ios/fastlane/test_output/xctest/ios/RevenueCat.xcresult))
```

**Comment by NachoSoto** [comment]
I just rebased this off of #3650 which I think will fix that.

**Comment by NachoSoto** [comment]
@MarkVillacampa feel free to merge this :)

**Pull request merged**
