### PR TITLE
[Customer Center] Fix `FeedbackSurveyView` not opening

### PR DESCRIPTION
**Pull request by vegaro**
For some reason, the dismiss environment variable was causing the view to constantly recreate, which was causing a loop when trying to launch the feedback survey view, and the app would freeze.

I moved the `dismiss` to the `DismissCircleButton` and looks like it has solved it.

### CODE REVIEW

**Review by JayShortway — APPROVED** [review]
Good find! Will update my PR (https://github.com/RevenueCat/purchases-ios/pull/4193) when this is merged.

**Comment by JayShortway** [comment]
What's happening with SwiftLint? Since when is exit code 0 an error? Also, [this report](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/21715/workflows/86c7c1f9-3741-4c30-b1d2-74f8f8d7210b/jobs/253272/tests) makes no sense, as that disable is definitely doing something. I'm getting the same in my other PR (https://github.com/RevenueCat/purchases-ios/pull/4199).

**Review by codykerns — APPROVED** [review]

**Comment by vegaro** [comment]
yeah, that's weird, I am not getting it locally

**Comment by vegaro** [comment]
ok @JayShortway I had to upgrade Swiftlint locally to see the issue, looking into it

**Pull request merged**
