### PR TITLE
Fix winback tests on iOS 14 & API Tester

### PR DESCRIPTION
**Pull request by fire-at-will**
This PR addresses a few issues with some tests that aren't normally covered by the `build-test` workflow. 

Specifically, it addresses two issues:
- The async version of `fulfillment()` wasn't introduced until Xcode 13/Swift 5.5/iOS 15. This PR removes the affected tests from compilation on Swift compiler versions <6.0. This won't affect our test coverage of the win-backs feature since win-backs aren't available on iOS versions below 18.
- Adds a few items from https://github.com/RevenueCat/purchases-ios/pull/4431 to the Obj-C and Swift API testers

### CODE REVIEW

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Comment by fire-at-will** [comment]
@RCGitBot please test

**Review by vegaro — APPROVED** [review]

**Comment by fire-at-will** [comment]
The `deploy-purchase-tester-2` job failed, but that's also failing in main, so merging anyways to get these fixes in

**Pull request merged**
