### PR TITLE
version 3.9.1

### PR DESCRIPTION
**Pull request by aboedo**
## 3.9.1
- Added support for `SKPaymentQueue`'s `didRevokeEntitlementsForProductIdentifiers:`, so entitlements are automatically revoked from a family-shared purchase when a family member leaves or the subscription is canceled.
    https://github.com/RevenueCat/purchases-ios/pull/413

### CODE REVIEW

**Comment by aboedo** [comment]
there are a couple of integration tests that are failing, those are fixed in https://github.com/RevenueCat/purchases-ios/pull/411/
We can either include the code or trust it @vegaro

**Review by vegaro — APPROVED** [review]

**Comment by vegaro** [comment]
Let's trust it

**Comment by aboedo** [comment]
@vegaro heads up, I accidentally merged the CI deploys PR before this one 🤦. It was already approved, though. 
The good news is that integration tests should be fixed, though, and since it's only CI stuff, there's no risk of adding user-facing issues with the other PR.

**Comment by aboedo** [comment]
right, forgot about this from last week: deployment-checks fail until #412 is merged. It shouldn't be an issue, though.

**Comment by aboedo** [comment]
come to think about it, yeah, it might be an issue for CI deploys. @vegaro would you mind checking out #412 so we can include it here? It's also CI-specific so no risk of customer-facing issues

**Comment by aboedo** [comment]
update: the issues in deployment-checks aren't related to the SPM thing, they're related to #365 and fixed in #419

**Pull request merged**
