### PR TITLE
ProductsFetcherSK2: improved Error information

### PR DESCRIPTION
**Pull request by NachoSoto**
Adding this on top of #1017 

Trying to figure out this error:
```xml
<testcase classname="StoreProductTests" name="testSk2DetailsWrapsCorrectly()" time="6.029647946357727">
<failure message="failed: caught error: "The operation couldn’t be completed. (RevenueCat.ProductsManagerSK2Error error 0.)" (#CharacterRangeLen=0)"></failure>
</testcase>
```

### CODE REVIEW

**Comment by NachoSoto** [comment]
Yet another error:
```
productsRequestError(innerError: StoreKit.StoreKitError.systemError(Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.storekitservice.sim2host was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.storekitservice.sim2host was invalidated: failed at lookup with error 3 - No such process.}))
```

**Comment by NachoSoto** [comment]
This is ready for review.

**Review by taquitos — COMMENTED** [review]
I like these changes, any ideas about the test failures?

**Comment by NachoSoto** [comment]
> I like these changes, any ideas about the test failures?

Seems like a backend problem? Let me re-run those.

**Comment by NachoSoto** [comment]
Still failing intermittently in CI.

Here's where we (I think) are:

- I deleted the artificial 30 second delay at the beginning of all `StoreKitConfigTestCases`
- Without that tests pretty much always used to fail in CI
- The new retry mechanism makes tests pass most of the time now... MOST
- The failures now come from the timeout in `ProductsFetcherSK1` or in the timeouts specified by our `toEventually()`s.
- So I believe the PR is a decent solution for users in production. Most of the time they won't see issues similar to what we see in CI. However, CI still sees intermittent failures, and my best explanation is that it's due to their slow hardware.

So what I suggest is to add the delay only in CircleCI (detecting an environment variable), so we don't artificially slow down the tests when running them locally, which don't need such a mechanism on normal hardware.

Thoughts @aboedo @taquitos?

**Comment by taquitos** [comment]
I like the idea of the env var for CI. CI is definitely slower than local. If you give me a name/default value I can add that now.

**Comment by NachoSoto** [comment]
[`CircleCI` already has a few](https://circleci.com/docs/2.0/env-vars/), including `CIRCLECI`, so we can use that. What do you think?

**Comment by taquitos** [comment]
Oh, I was thinking we set a `CIRCLECI_DELAY_SECONDS` variable so we can tune it without rebuilding 😄

**Comment by NachoSoto** [comment]
That sounds great 👍  Maybe `CIRCLECI_STOREKIT_TESTS_DELAY_SECONDS`?

**Comment by taquitos** [comment]
Ok, I added it and set it to `30`

**Comment by NachoSoto** [comment]
Done: a612b8ece45e2d123547ee9ca5c60aa8522ae817

**Comment by NachoSoto** [comment]
> <failure message="Test crashed with signal ill. (#CharacterRangeLen=0)"></failure>

😑

**Comment by NachoSoto** [comment]
Okay, let's hope the intermittent failures are gone?

**Review by taquitos — APPROVED** [review]
⏲️  👣  🐐

**Pull request merged**
