### PR TITLE
Make StoreProduct initializers public

### LINKED ISSUE #1340: StoreProduct public initializer [4.0.0-rc.4]
Hi,

In some cases, we need to initiate a purchase with a `SKProduct` but the new API only takes `StoreProduct` as a parameter and doesn't provide a public initializer for `StoreProduct` ([see L242](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift#L242)).

```swift
class PaywallManager: PaywallDelegate {
    func purchase(product: SKProduct) {
        let product = StoreProduct(sk1Product: product) // <- we can't do that

        Purchases.shared.purchase(product: product) { transaction, purchaserInfo, error, userCanceled in
              // ....
        }
    }
```

Could we have public `StoreProduct` initializers ? Thanks !

### PR DESCRIPTION
**Pull request by delba**
Resolves #1340

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]
I think this makes sense but I'd like one more set of 👀 on it before merging 😊 

Really appreciate the PR ❤️

**Comment by NachoSoto** [comment]
I think we can merge this. Just need to add it to the `APITester`s afterwards.

**Comment by aboedo** [comment]
Agreed that we can merge and we should add @objc, we can do that in a separate PR if needed

**Comment by aboedo** [comment]
@delba thanks for the suggestion and for opening up the PR!!

**Pull request merged**
