### PR TITLE
`StoreKit2` listeners: set `Task` `priority` to `.utility`

### PR DESCRIPTION
**Pull request by NachoSoto**
A small performance improvement, since technically these don't need higher priorities.

### CODE REVIEW

**Comment by aboedo** [comment]
🤔 neither of them should happen often so it shouldn't make a difference in practice, but I do feel like that might be more of an argument for updating as quickly as possible if they do happen, particularly for transactions. No strong feelings about this one, though

**Comment by NachoSoto** [comment]
Yeah I can see either way. The way I was thinking about it is that this is something that the SDK is running in the background and shouldn't have a very high priority that could potentially make the UI of an app slow down or drop frames.

But maybe "utility" would make more sense?
From the docs:
> Utility priority is intended for user-visible tasks such as fetching data from the network, copying files, or importing data.

**Comment by aboedo** [comment]
that seems pretty applicable

**Comment by NachoSoto** [comment]
Changed!

**Review by aboedo — APPROVED** [review]

**Pull request merged**
