### PR TITLE
`Xcode 15.3`: fix warnings on Integration Tests

### PR DESCRIPTION
**Pull request by NachoSoto**
Follow up to #3599 and #3600.

These `@MainActor` annotations don't work anymore because of this:
> Main actor-isolated class '...' has different actor isolation from nonisolated superclass 'TestCase'; this is an error in Swift 6

They were necessary with an older version of Xcode (likely 13.x), but not anymore.

### CODE REVIEW

**Review by MarkVillacampa — APPROVED** [review]

**Comment by NachoSoto** [comment]
Unfortunately removing these `@MainActor` (which produce a warning with Xcode 15.2)` leads to crashes running the tests:
```
2024-01-29 17:36:56.806437+0000 BackendIntegrationTestsHostApp[10530:37574] *** Assertion failure in -[XCTestObservationCenter addTestObserver:], XCTestObservationCenter.m:108
2024-01-29 17:36:56.807637+0000 BackendIntegrationTestsHostApp[10530:37574] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Test observers can only be registered and unregistered on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
	2   Foundation                          0x0000000180ae29b4 _userInfoForFileAndLine + 0
	3   XCTestCore                          0x0000000109bece24 -[XCTestObservationCenter addTestObserver:] + 296
	4   BackendIntegrationTests             0x000000010ad94a7c $s15SnapshotTesting28CleanCounterBetweenTestCases33_C4D615B58D7827966DB6A592ACD75CB2LLC16registerIfNeededyyFZyyXEfU_ + 216
	5   BackendIntegrationTests             0x000000010ad94adc $sIg_Ieg_TR + 20
	6   BackendIntegrationTests             0x000000010ad94b00 $sIeg_IyB_TR + 24
	7   libdispatch.dylib                   0x0000000180134708 _dispatch_client_callout + 16
	8   libdispatch.dylib                   0x0000000180144ec4 _dispatch_lane_barrier_sync_invoke_and_complete + 92
```

**Comment by NachoSoto** [comment]
Oh no nevermind, it's because this is broken in `swift-snapshot-testing`:

```swift
private class CleanCounterBetweenTestCases: NSObject, XCTestObservation {
    private static var registered = false
    private static var registerQueue = DispatchQueue(label: "co.pointfree.SnapshotTesting.testObserver")

    static func registerIfNeeded() {
      registerQueue.sync {
        if !registered {
          registered = true
          XCTestObservationCenter.shared.addTestObserver(CleanCounterBetweenTestCases())
        }
      }
    }

    func testCaseDidFinish(_ testCase: XCTestCase) {
      counterQueue.sync {
        counterMap = [:]
      }
    }
}
```

**Comment by NachoSoto** [comment]
Blocked by this: https://github.com/pointfreeco/swift-snapshot-testing/issues/661

Updating `swift-snapshot-testing` once that's fixed will require dropping iOS 12 support, which depends on #3615.

**Comment by MarkVillacampa** [comment]
Submitted a PR to the `swift-snapshot-testing` library https://github.com/pointfreeco/swift-snapshot-testing/pull/834

**Pull request merged**
