### PR TITLE
changes unicode to emoji

### PR DESCRIPTION
**Pull request by tiinanguyen**
@aboedo pointed out that we can use the emoji instead of the unicode. I did a test with all the log methods and this is true. Github shows the representation differently for some emojis, but this shows properly in Xcode.

### CODE REVIEW

**Review by aboedo — APPROVED** [review]

**Comment by aboedo** [comment]
We could even omit the struct and use the emojis directly come to think about it

**Review by aboedo — APPROVED** [review]
❤️ it

**Comment by aboedo** [comment]
but you need to remove `Emojis.swift` file from the xcproject as well, not just the file system. or maybe that's done but you need to commit the changes to the xcproject file

**Review by tiinanguyen — COMMENTED** [review]
@aboedo Just added that commit. Good to go?

**Comment by aboedo** [comment]
yep! 🚢

**Pull request merged**
