### PR TITLE
Prepare next version: 4.6.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by revenuecat-ops**

### CODE REVIEW

**Review by aboedo — APPROVED** [review]

**Comment by aboedo** [comment]
@NachoSoto it does add the changelog from 4.5.1

I'm not sure why the other changes are even showing, though, shouldn't everything else already be set to  `4.6.0-SNAPSHOT`?

**Comment by NachoSoto** [comment]
I know that confused me too 🧐

**Comment by NachoSoto** [comment]
I bet if we rebase this branch it would show an empty diff?

**Comment by aboedo** [comment]
@NachoSoto rebased, now we get the changelog 👍

**Review by NachoSoto — APPROVED** [review]

**Pull request merged**
