### PR TITLE
Fixed `AttributionFetcher.adServicesToken` hanging when called in simulator

### LINKED ISSUE #2121: App freezes on iOS 14.5 after calling enableAdServicesAttributionTokenCollection()
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Development/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
When calling `Purchases.shared.attribution.enableAdServicesAttributionTokenCollection()` the app will freeze on iOS 14.5.

I call this during app startup, after configuring the SDK and my app freezes on the Launch Screen. I tried moving it to later in the app cycle and the app freezes as soon as this is called.

1. Environment
   1. Platform: iPhone and iPad Simulator
   2. SDK version: 4.15.0
   3. StoreKit 2 (_disabled with `useStoreKit2IfEnabled(false)`_) (Y/N):
   4. OS version: iOS 14.5
   5. Xcode version: 14.1
   6. How widespread is the issue. Percentage of devices affected.

**Additional context**

Reported by multiple users here: https://community.revenuecat.com/sdks-51/calling-enableadservicesattributiontokencollection-on-ios-14-5-seems-to-hang-my-app-2010

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #2121 and [CSDK-600].

Initially I wanted to check `.toNot(beEmpty())`, but at least locally it's throwing an error:
> Error Domain=com.apple.ap.adservices.attributionError Code=2 "Error generating token" UserInfo={NSLocalizedDescription=Error generating token}

Which is `AAAttributionError.Code.internalError`.
At least we have some test coverage to see if in any combination of Xcode / iOS it hangs, as reported.

[CSDK-600]: https://revenuecats.atlassian.net/browse/CSDK-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NachoSoto** [comment]
And looks like this fails in iOS 14 only:
Screenshot 2022-12-15 at 09 37 49

**Comment by NachoSoto** [comment]
Perfect!

**Comment by NachoSoto** [comment]
Tests pass!

**Comment by NachoSoto** [comment]
I'd file a Radar, but this looks fixed in iOS 15/16, so they're gonna close it as "fixed" anyway.

**Review by aboedo — APPROVED** [review]

**Pull request merged**
