### PR TITLE
Add tests to ensure that `HTTPClient` calls the DNS checker

### LINKED ISSUE #1131: Add test that ensures that `HTTPClient` actually calls the DNS checker
We test the DNSChecker but we don't ensure the HTTPClient calls it 🤦‍♂️

### PR DESCRIPTION
**Pull request by Juanpe**
Resolves #1131

This PR adds tests to ensure that `HTTPClient` actually calls the DNS checker.

`DNSChecker` is an `enum` with static methods and because of that, it's hard to create tests related to these methods. So, I've created a protocol called `DNSCheckerType` to describe all the static methods. Also, I've defined a property of this type as a dependency of the `HTTPClient`.

For the tests, I've created a DNSChecker spy to know when a static method has been called.

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
Big fan of this change. Protocols  FTW 😄

**Review by aboedo — COMMENTED** [review]
Looks great so far! 

We're [currently using the DNSChecker to decide whether or not to log an error](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Networking/HTTPClient.swift#L228). 

Perhaps we should add a check? Otherwise, if we entirely modified the behavior of DNSChecker, `HTTPClientTests` would still pass. 

I think we can use the logHandler property to ensure that a log has been issued if `isBlockedAPIError` is `true` and it hasn't if `false`

**Comment by Juanpe** [comment]
> Looks great so far!
> 
> We're [currently using the DNSChecker to decide whether or not to log an error](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Networking/HTTPClient.swift#L228).
> 
> Perhaps we should add a check? Otherwise, if we entirely modified the behavior of DNSChecker, `HTTPClientTests` would still pass.
> 
> I think we can use the logHandler property to ensure that a log has been issued if `isBlockedAPIError` is `true` and it hasn't if `false`

Thanks for the feedback 👍🏼 

🤔 You mean replace the current spy with a logHandler right? Yep, it could be another way to check that DNS checker is called. My concern is that we have to be sure that this error is always logged after validating the response error. Also, we have to check the logged message and if we modify the translations, this test would fail, right? 

I realized that we might have another problem after setting the logHandler property. That is, being a static property, once it is modified, this change will be there for the rest of the test cases. Do you know what I mean?
```swift
var logHandlerCalled = false
Logger.logHandler = { _, _, _, _, _ in
    logHandlerCalled = true
}
```

WDYT?

**Comment by aboedo** [comment]
I think I didn't explain my thinking well. 

My thinking was to _in addition_ to the current spy and tests (which I love), we add a new test, that still uses the existing spy, and: 
- sets up the `Loghandler` as a spy, like you mentioned. We can have the existing `logHandler` stored in a variable of type `VerboseLogHandler` as a backup so that in the `tearDown` code we replace it after being done, that way we don't mess up other tests
- forces the result of `isBlockedAPIErrorCalled` to `true`
- checks that the logHandler is called when `isBlockedAPIErrorCalled` is `true`

And the equivalent for `false`. 

It'd technically transform the spy into a mock I suppose if we're modifying the return values. Or rather a partial mock if it's just for the one method. 

Hope that clarifies the suggestion! Let me know if it's still unclear, I think the summer heat is getting to me 😂

**Comment by Juanpe** [comment]
Ahh ok ok, yep, it makes more sense for me 👍🏼 Let me do the changes 🙂

**Comment by Juanpe** [comment]
I made the suggested changes. I've added two new test methods. But I'm not sure if we should check the logged message as well. If the logger is called previously, the tests could pass too. WDYT?

**Comment by aboedo** [comment]
nice job! 

>  But I'm not sure if we should check the logged message as well. If the logger is called previously, the tests could wrongly pass. WDYT?

This is a valid concern. Yeah, checking the logged message would solve it. If we check against the `NetworkStrings.blocked_network(newHost:)` string we'd be able to make sure that if the copy gets updated, the test will still work.

Alternatively, we could keep a call count instead of a bool but that's more brittle for sure. 
I still think this is better than what we had before the PR, so I'm happy to merge if you'd like, but otherwise feel free to add a check for the message. LMK what you think!

**Comment by Juanpe** [comment]
> Alternatively, we could keep a call count instead of a bool but that's more brittle for sure.

Yeah, keeping a call count is more fragile 😕 
Finally, I've stored all logged messages, so we only have to check if this array contains the expected message. 

IMO, after this change, this PR would mark as done. But let me know if you think we should make some changes, ok? 🤙

**Review by aboedo — APPROVED** [review]
@Juanpe looks fantastic! Looks like there are merge conflicts from https://github.com/RevenueCat/purchases-ios/pull/1113, we're good to merge after solving them!

**Comment by Juanpe** [comment]
> @Juanpe looks fantastic! Looks like there are merge conflicts from #1113, we're good to merge after solving them!

Great! 🚀 

I've updated the tests considering that now we return an error too. 

BTW, [I've moved `DNSError` out of to `DNSChecker` type](https://github.com/RevenueCat/purchases-ios/blob/2603b67eefb847184b59151e470d617816ccbbfb/Purchases/Networking/DNSChecker.swift#L25) because we are now using the abstraction `DNSCheckerType` instead of the implementation, so it doesn't make sense the error is a subtype of `DNSChecker`. Let me know if looks good for you 👍🏼

**Comment by aboedo** [comment]
> BTW, I've moved DNSError out of to DNSChecker type because we are now using the abstraction DNSCheckerType instead of the implementation, so it doesn't make sense the error is a subtype of DNSChecker. Let me know if looks good for you 👍🏼

Great call!! 

Thanks for updating the PR! Merging now. Great job on this!

**Pull request merged**
