### PR TITLE
Extracted `PurchasesOrchestrator.extractProductIdentifier` to `SK1Product` extension

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes [sc-11121].

### CODE REVIEW

**Comment by NachoSoto** [comment]
I may be missing some context here so let me know if there's anything else to it?

**Review by aboedo — APPROVED** [review]
haha nope, it was a short one. 

We should also update `SK1StoreProduct` so it uses this instead of the potentially-nil `productIdentifier` from `SKProduct`

**Comment by NachoSoto** [comment]
> We should also update SK1StoreProduct so it uses this instead of the potentially-nil productIdentifier from SKProduct

But this implementation needs an `SKPayment`, which we don't always have?

**Comment by NachoSoto** [comment]
I'll merge this for now, but @aboedo when you're back let me know if I'm missing something. It looks like we can't easily use it anywhere else because this uses the `Payment`.

**Comment by aboedo** [comment]
Right, I'd missed the usage of the `SKPayment`, looks like this is as good as we'll get for now.

**Pull request merged**
