### PR TITLE
Adds an `onDismiss` callback to `ErrorDisplay`

### PR DESCRIPTION
**Pull request by JayShortway**
As the title says, and as discussed on Slack. This is needed for https://github.com/RevenueCat/purchases-kmp/issues/217.

### CODE REVIEW

**Comment by JayShortway** [comment]
Not sure about the labels. Went with `force_minor` because it's not a bug fix, and SemVer says patch is for bug fixes only. Open to suggestions.

**Comment by JayShortway** [comment]
@RCGitBot please test

**Review by joshdholtz — APPROVED** [review]
This looks good to me! :shipit:

**Comment by JayShortway** [comment]
Changed it back to `force_patch` haha. It kinda is a bug fix, but for purchases-kmp. Still open to suggestions.

**Pull request merged**
