### PR TITLE
Changed several PurchaserInfo to ConsumerInfo

### PR DESCRIPTION
**Pull request by NachoSoto**
NFC (non-functional-change)

### CODE REVIEW

**Review by aboedo — APPROVED** [review]
Good catch! Most of these were in the `storekit_2` branch while the `main` branch had the rename

**Comment by NachoSoto** [comment]
Hehe makes sense.

**Comment by NachoSoto** [comment]
Trying to figure out why this isn't working on my migration... realized I've gotten this wrong 🤦 
Screen Shot 2021-11-30 at 12 01 28

**Comment by taquitos** [comment]
LOL.

**Pull request merged**
