### PR TITLE
Cleanup: Remove test storekit configuration files when importing through SPM

### PR DESCRIPTION
**Pull request by aboedo**
Alternative approach to #3876, where in this one we _only_ add the Package.swift file. 
That was the most important part in any case. 

I would still love to clean up the project structure, but it's a much bigger change.

### CODE REVIEW

**Comment by aboedo** [comment]
can confirm that it still works: 

image


Now we just need to see whether tests still run correctly

**Comment by aboedo** [comment]
This has been bugging me for so long it's kind of crazy that the solution was this simple

**Review by jamesrb1 — APPROVED** [review]
Works like a charm.

**Review by tonidero — APPROVED** [review]
🙌

**Comment by vegaro** [comment]
I've noticed that after this change, the `Tests` folder stopped appearing in xcode when opening the SPM project, which is the only way I know to work on `RevenueCatUI` tests. The xcodeproj doesn't have the RevenueCatUI test files (nor the source files)

**Pull request merged**
