### PR TITLE
cleaned up docs for the configure method

### PR DESCRIPTION
**Pull request by aboedo**
| Before | After |
| :-: | :-: |
| Screen Shot 2022-05-26 at 6 46 07 PM | Screen Shot 2022-05-26 at 6 46 57 PM |

Also added an example: 
Screen Shot 2022-05-26 at 6 45 11 PM

### CODE REVIEW

**Review by NachoSoto — APPROVED** [review]
Love it

**Comment by NachoSoto** [comment]
What do you think about adding this example to the release notes once the release comes out in GitHub?

**Comment by aboedo** [comment]
@NachoSoto great idea! I'll do that

**Comment by aboedo** [comment]
@NachoSoto done! lmk what you think

**Comment by NachoSoto** [comment]
Perfect!

**Pull request merged**
