### PR TITLE
`CustomerInfo`: added missing `hash` implementation

### PR DESCRIPTION
**Pull request by NachoSoto**

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
#️⃣er 🐐

**Comment by winstondu** [comment]
@taquitos , does this fix any issues?

**Comment by NachoSoto** [comment]
This isn't fixing any known issue, just happened to notice `CustomerInfo` had a custom `isEqual:` but not `-hash`, so it *could* lead to issues when used inside a `Set` for example.

**Comment by taquitos** [comment]
We left it out because in RCv3 it was left out. When we migrated from ObjC we decided to migrate as-is, no improvements. Then once we finished, we could iterate. This is one of those things we hadn't gotten to 😄

**Pull request merged**
