### PR TITLE
updated usage of `Purchases.PurchaserInfo` -> `PurchaserInfo` in purchaseTester

### PR DESCRIPTION
**Pull request by aboedo**
Updated usage of Purchases types in PurchaseTester

### CODE REVIEW

**Review by taquitos — COMMENTED** [review]
I *think* we want to leave this for now, then try to integrate the whole new SDK and all of the new API at once via https://github.com/RevenueCat/purchases-ios/issues/740
@beylmk what do you think?

**Comment by aboedo** [comment]
note that we still have the MagicWeather app and the legacy tester app (which is almost identical to this one), so this is only hampering our own ability to test the SDK. 
in particular, it's super annoying when I test out SK2 stuff

**Comment by beylmk** [comment]
> note that we still have the MagicWeather app and the legacy tester app (which is almost identical to this one), so this is only hampering our own ability to test the SDK.
> in particular, it's super annoying when I test out SK2 stuff

oops sorry for the late response. as long as we have one app consuming the old SDK, i'm ok with it! we'll probably have to build either one out anyway, to ensure all public APIs are called..

**Review by beylmk — APPROVED** [review]
🔥

**Pull request merged**
