### PR TITLE
[AUTOMATIC] Release/4.16.0

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

### New Features
* Created `ReceiptParser` SPM (#2155) via NachoSoto (@NachoSoto)
* Exposed `PurchasesReceiptParser` and `AppleReceipt` (#2153) via NachoSoto (@NachoSoto)
### Bugfixes
* `Restore purchases`: post product data when posting receipts (#2178) via NachoSoto (@NachoSoto)
### Other Changes
* Added `Dictionary.merge` (#2190) via NachoSoto (@NachoSoto)
* `CircleCI`: use Xcode 14.2.0 (#2187) via NachoSoto (@NachoSoto)
* `ReceiptParser`: a few documentation improvements (#2189) via NachoSoto (@NachoSoto)
* `Purchase Tester`: fixed `TestFlight` deployment (#2188) via NachoSoto (@NachoSoto)
* `Purchase Tester`: display specific `IntroEligibilityStatus` (#2184) via NachoSoto (@NachoSoto)
* `Purchase Tester`: fixed `SubscriptionPeriod` (#2185) via NachoSoto (@NachoSoto)

### CODE REVIEW

**Review by NachoSoto — APPROVED** [review]

**Comment by NachoSoto** [comment]
New `ReceiptParser` installation test passed 🎉

**Comment by NachoSoto** [comment]
I wanted to make sure CI was all passing with the new SPM. But should we hold this until next week?

**Comment by aboedo** [comment]
I'm around this week, I don't have reservations about shipping it this week

**Comment by NachoSoto** [comment]
Sounds good 👍🏻 
I'll have my laptop with me and can fight fires, but otherwise might not be around much until the 2nd.

**Pull request merged**
