### PR TITLE
[AUTOMATIC] Release/5.2.0

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

### New Features
* Added new paywall template to support multiple tiered subscriptions (#4022) via Josh Holtz (@joshdholtz)
### Bugfixes
* Fix certain completion blocks not being dispatched on the main thread (#4058) via Mark Villacampa (@MarkVillacampa)
* Only checks staged files for leftover API keys. (#4073) via JayShortway (@JayShortway)
### Other Changes
* [Ci] Fix trigger to run all tests from github actions  (#4075) via Andy Boedo (@aboedo)
* added new workflow to trigger all tests (#4051) via Andy Boedo (@aboedo)
* Reduce CI jobs (#4025) via Andy Boedo (@aboedo)

### CODE REVIEW

**Review by MarkVillacampa — APPROVED** [review]

**Comment by aboedo** [comment]
well, release-checks should now fail because the tag already exists

**Comment by aboedo** [comment]
unless I beat it to the punch

**Comment by aboedo** [comment]
(I cancelled release checks because I pushed the tag manually the second time, and it was before that job could run)

**Comment by joshdholtz** [comment]
@aboedo Going to merge this since everything but the docs is shipped 💪

**Review by joshdholtz — APPROVED** [review]
🚢

**Pull request merged**
