### PR TITLE
Re-enabled SK2

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes [sc-9602]

Screen Shot 2022-01-31 at 10 55 11

### CODE REVIEW

**Review by beylmk — APPROVED** [review]
🥳

**Comment by NachoSoto** [comment]
Just wanna confirm, are we good to merge this now that RC1 is already branched off?

**Review by aboedo — APPROVED** [review]
Looks great! But let's hold off just a little bit, since we'll have to rebase RC1 from main to include https://github.com/RevenueCat/purchases-ios/pull/1222, hopefully we can do that and ship RC1 tomorrow

**Comment by NachoSoto** [comment]
Good to merge now? :)

**Comment by NachoSoto** [comment]
Good to merge now? :)

**Review by aboedo — APPROVED** [review]
gonna add it to the changelog in rc 2

**Pull request merged**
