### PR TITLE
CircleCI: added job for iOS 16 tests

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes [CSDK-260].

### Depends on:
- #1698
- #1699
- #1700
- #1701

[CSDK-260]: https://revenuecats.atlassian.net/browse/CSDK-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NachoSoto** [comment]
[This](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7166/workflows/0171a56b-a13a-4ee4-8e57-b7d2d990cd2a/jobs/29262) isn't my issue, is it?

> Creating a dedicated VM with xcode:14.0.0 image
>
>Assigned VM request id: 236172730
  provisioning: .
>We had an unexpected error preparing a VM for this build, potentially due to our infrastructure or cloud provider.  Please retry the build in a few minutes
>
>Unexpected environment preparation error: failed to create a vm: VM creation failed

**Comment by NachoSoto** [comment]
_Re-running_

**Comment by joshdholtz** [comment]
@NachoSoto I re-ran this again this morning and failing on `Stored properties cannot be marked potentially unavailable with '@available'` which I think we fixed in the public API but seems like we might have an implementation of this in the tests? 🤔

**Comment by NachoSoto** [comment]
@joshdholtz haha of course. I'll send a PR fixing that.

**Comment by NachoSoto** [comment]
Tests are running now: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7187/workflows/9a5ae035-69ee-4ee7-ba2b-19c617651d3a/jobs/29405

Pending #1701 now.

**Pull request merged**
