### PR TITLE
[DO NOT MERGE] Release/4.18.0

### PR DESCRIPTION
**Pull request by NachoSoto**
### New Features
* Introduced Custom Entitlements Computation mode (#2439) via Andy Boedo (@aboedo)
* Create separate `SPM` library to enable custom entitlement computation (#2440) via NachoSoto (@NachoSoto)

This new library allows apps to use a smaller version of the RevenueCat SDK, intended for apps that will do their own entitlement computation separate from RevenueCat.

Apps using this mode rely on webhooks to signal their backends to refresh entitlements with RevenueCat.

See the [demo app for an example and usage instructions](https://github.com/RevenueCat/purchases-ios/tree/main/Examples/testCustomEntitlementsComputation).

### Bugfixes
* `PurchaseOrchestrator`: fix incorrect `InitiationSource` for SK1 queue transactions (#2430) via NachoSoto (@NachoSoto)

### Other Changes
* Update offerings cache when switchUser(to:) is called (#2455) via Andy Boedo (@aboedo)
* Updated example code for the sample app for Custom Entitlements (#2454) via Andy Boedo (@aboedo)
* Custom Entitlement Computation: API testers (#2452) via NachoSoto (@NachoSoto)
* Custom Entitlement Computation: avoid `getCustomerInfo` requests for cancelled purchases (#2449) via NachoSoto (@NachoSoto)
* Custom Entitlement Computation: disabled unnecessary APIs (#2442) via NachoSoto (@NachoSoto)
* `StoreKit1Wrapper`: added log when adding payment to queue (#2423) via NachoSoto (@NachoSoto)
* `StoreKit1Wrapper`: added debug log when transaction is removed but no callbacks to notify (#2418) via NachoSoto (@NachoSoto)
* `customEntitlementsComputation`: update the copy in the sample app to explain the new usage (#2443) via Andy Boedo (@aboedo)
* Clarify reasoning for `disfavoredOverload` in logIn (#2434) via Andy Boedo (@aboedo)
* Documentation: improved `async` API docs (#2432) via Kaunteya Suryawanshi (@kaunteya)

### CODE REVIEW

**Comment by NachoSoto** [comment]
This includes #2442 cherry-pick, which isn't approved yet. I can update the commit if any changes are required there.

**Comment by NachoSoto** [comment]
Updated release notes here.

**Comment by NachoSoto** [comment]
Just need to cherry-pick #2452, will do that in a couple of hours.

**Comment by aboedo** [comment]
@NachoSoto I cherry-picked it to 4.17.11 and rebased 4.18.0 on that one, since it looked like that was the logic applied to the rest of the commits

**Comment by NachoSoto** [comment]
Yup perfect!

**Comment by aboedo** [comment]
APITester doesn't work because it's using `main`, and in `main` we have a reference to `signatureVerificationFailed` in API tests (from Trusted Entitlements)

**Comment by NachoSoto** [comment]
> APITester doesn't work because it's using main

It shouldn't be using `main`, the CircleCI job is supposed to change `main` to the commit hash it's testing. Investigating.

**Comment by NachoSoto** [comment]
Oh I see, we needed to modify the cherry-picked commit slightly to accommodate the current API in that branch. Fixing.

**Comment by NachoSoto** [comment]
Fixed, rebasing.

**Comment by NachoSoto** [comment]
Release notes added in #2461.

**Pull request closed without merging**
