### PR TITLE
[AUTOMATIC] Release/4.23.0

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

_This release is compatible with `Xcode 15 beta 2` and `visionOS beta 1`_

### New Features
* `xrOS`: added to list of supported platforms (#2682) via NachoSoto (@NachoSoto)
### Bugfixes
* `xrOS`: fixed compilation by disabling debug overlay (#2681) via NachoSoto (@NachoSoto)
* `xrOS`: added support for new `purchase(confirmIn:options:)` method (#2683) via NachoSoto (@NachoSoto)
* `Xcode 15`: handle `Locale.currencyCode` deprecation (#2680) via NachoSoto (@NachoSoto)
### Other Changes
* `PurchaseTester`: fixed release compilation (#2689) via NachoSoto (@NachoSoto)
* `xrOS`: fixed runtime warning (#2691) via NachoSoto (@NachoSoto)
* `xrOS`: added support to `PurchaseTester` (#2685) via NachoSoto (@NachoSoto)
* `Signature Verification`: new `Integration Tests` (#2642) via NachoSoto (@NachoSoto)
* `ErrorUtils`: handle `PurchasesError` to avoid creating unknown errors (#2686) via NachoSoto (@NachoSoto)

### CODE REVIEW

**Comment by NachoSoto** [comment]
I broke `watchOS` on `PurchaseTester`, I'll fix it.

**Review by NachoSoto — APPROVED** [review]

**Comment by abbana** [comment]
[!] The platform of the target `` (visionOS 1.0) is not compatible with `RevenueCat (4.23.1)`, which does not support `visionOS`.

I think you should add visionos as named in cocoapods upcoming 1.13 release https://github.com/CocoaPods/CocoaPods/issues/11961

**Comment by NachoSoto** [comment]
Thanks! We'll keep an eye on that CocoaPods release and add support for `visionOS` when that's out.

**Comment by abbana** [comment]
Hi @NachoSoto can you please do it ASAP so I can port my app and having the users ready to make purchases from early 2024? CocoaPods next offifical release will be out too late for me to have that done on time.
Thanks.

**Comment by NachoSoto** [comment]
Are you using a manual build of CocoaPods?

Alternatively you could use SPM for RevenueCat.

**Comment by NachoSoto** [comment]
We can look into it, but do you happen to know if releasing a Pod with `visionos` would break anyone using it with the latest release of CocoaPods?

**Comment by abbana** [comment]
That would be helpfult, thanks.

No, I do not have an answer to that question, sorry.

**Pull request merged**
