### PR TITLE
Migrates RCDateProvider

### LINKED ISSUE #542: Migrate RCDateProvider

### PR DESCRIPTION
**Pull request by joshdholtz**
Thank you for contributing to Purchases. Before pressing the "Create Pull Request" button, please provide the following:

  - [x] A description about what and why you are contributing, even if it's trivial.

  - [x] The issue number(s) or PR number(s) in the description if you are contributing in response to those.

  - [x] If applicable, unit tests.

Fixes #542

- Removed `Purchases/Misc/RCDateProvider.h`
- Added `PurchasesCoreSwift/Misc/DateProvider.swift`
  - `DateProvider` is an `open class` so that `MockDateProvider` can subclass

### CODE REVIEW

**Comment by joshdholtz** [comment]
Closing because I used wrong branch 🤷‍♂️ Opening another because rebase didn't work correctly.

**Comment by joshdholtz** [comment]
Reopening because I can just force push branch 🙈

**Comment by joshdholtz** [comment]
This PR is great! LGTM 🎈🐐 

😉

**Comment by jeiting** [comment]
⭐  ⭐  Open 🌈  Source ⭐  ⭐

**Review by aboedo — APPROVED** [review]
Thanks for opening @joshdholtz !! 🎉 🚀

**Review by taquitos — APPROVED** [review]
This is beautiful. Thank you @joshdholtz

**Comment by joshdholtz** [comment]
image

**Pull request merged**
